# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

conda:
  environment: docs/environment.yml
  
# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html 
  configuration: docs/source/conf.py

  
formats:
  - pdf

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: docs/environment.yml
